### ISSUE TITLE
Add "no pronouns" option to !pronountest

### ISSUE THREAD

**Issue by NeoMahler** [NeoMahler/BinaryBot#28]
Use the name everywhere.

**Comment by Gopherslol** [comment]
I might be able to tackle this. Shouldn't be too difficult and could be a good way to learn my way around the codebase better

**Comment by NeoMahler** [comment]
That would be great! Let me know if you need help with anything.

**Comment by Gopherslol** [comment]
Alright, will do. Not sure how long it will take, this will be my first contribution, so I am still figuring out how everything works here

**Comment by NeoMahler** [comment]
Sure! You'll find the !pronountest command in the modules/nbdb.py file.

**Comment by NeoMahler** [comment]
Done!
